properties
sonar.projectKey=taskly-mobile-app
sonar.projectName=Taskly
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**, .expo/**, android/**, ios/**, dist/**