sonar.projectKey=taskly-mobile-app
sonar.projectName=Taskly
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**/*.ts,src/**/__tests__/**/*.tsx,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=node_modules/**, .expo/**, android/**, ios/**, dist/**, src/**/__tests__/**, src/**/*.test.ts, src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8